### ISSUE TITLE
iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by chmouel** [redhat-developer-demos/knative-minishift#6]
I am trying to follow the instructions and while spinning up knatives pod i have some errors in activator and autoscaler : 

```
NAME                          READY     STATUS                  RESTARTS   AGE
activator-5f9c4f5f49-fr4km    0/2       Init:CrashLoopBackOff   14         49m
autoscaler-57f8bdbd8b-j2d7f   0/2       Init:CrashLoopBackOff   14         49m
controller-86ccb7dfb9-5sc8s   1/1       Running                 0          49m
webhook-668d49668d-w9j9t      1/1       Running                 0          49m
```

looking at the error : 

```
 % oc logs pod/activator-5f9c4f5f49-fr4km -c istio-init
[...]
+ iptables -t nat -N ISTIO_REDIRECT
+ iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001
iptables: No chain/target/match by that name.
```

it's failing on the iptables redirection,

I am doing minishift install from OSX if that's change anything,

**Comment by chmouel** [comment]
FYI if I do : 

```
% minishift ssh
$ sudo iptables -t nat -N ISTIO_OUTPUT
$ sudo iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
$ sudo iptables -t nat -N ISTIO_REDIRECT
$ sudo iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001
```

It then runs properly : 

```
NAME                          READY     STATUS    RESTARTS   AGE
activator-5f9c4f5f49-fr4km    2/2       Running   0          59m
autoscaler-57f8bdbd8b-j2d7f   2/2       Running   0          59m
controller-86ccb7dfb9-5sc8s   1/1       Running   0          59m
webhook-668d49668d-w9j9t      1/1       Running   0          59m
```

In case that may help others,

**Comment by burrsutter** [comment]
Thank you!  Totally helped me!

**Comment by kameshsampath** [comment]
@chmouel  - until the API gets stable the crash backloops are kind of common (as we deploy from latest) :) .. but to answer your questions it looks like more of `privileged` issue with init containers which was removed by default for v1.0.1 and above of Isito, hence you might require do the configmap update as told in the instructions before you deploy knative* .

**Comment by chmouel** [comment]
No worries @kameshsampath this is expected, I was just documenting this for others if they find themselves onto the same issue, I am pretty sure I applied all the steps unless things changed since two week ago when I opened this,
