### ISSUE TITLE
The specified key does not exist

### ISSUE THREAD

**Issue by jsalcedo1987** [redhat-developer-demos/knative-minishift#9]
The following step is giving me an error because I think that this yaml does not longer exists:

```
curl -L https://storage.googleapis.com/knative-releases/serving/latest/release-no-mon.yaml \
  | sed 's/docker.io\/istio\/.*$/maistra\/proxyv2-centos7:0.3.0/' \
  | sed 's/istio-pilot:8080/istio-pilot.istio-system:15005/' \
  | oc apply -f -`
```

I think that this yaml should be replaced by:

```
https://storage.googleapis.com/knative-releases/serving/latest/serving.yaml
https://storage.googleapis.com/knative-releases/build/latest/build.yaml
```

Thanks,

**Comment by kameshsampath** [comment]
@jsalcedo1987  - this was experimental repo , please use the official docs https://github.com/openshift-cloud-functions/Documentation for OpenShift  and official docs of Knative for any other platform
